FIELDS = [
    'Resume_ID',
    'Name',
    'Email',
    'Phone Number',
    'LinkedIn URL',
    'Github/Portfolio URL',
    'Skills',
    'Technical Skills',
    'Soft Skills',
    'Languages',
    'Experience (Years)',
    'Education',
    'Certifications',
    'Job Role',
    'Current Employer',
    'Previous Employer',
    'Recruiter Decision',
    'Salary Expectation ($)',
    'Notice Period',
    'Availability',
    'Projects Count',
    'Achievements',
    'AI Score (0-100)',
    'Summary/Profile',
    'Desired Job Type',
    'Willing to Relocate',
    'Preferred Work Location',
    'Job Title',
    'Job Experience Required',
    'Key Skills',
    'Role Category',
    'Location',
    'Functional Area',
    'Industry',
    'Role',
    'Longitude',
    'Latitude',
    'sal',
    'Date of Birth',
    'Nationality',
    'Marital Status',
    'Gender',
    'Expected Joining Date',
    'Linked Projects URLs',
    'Freelance Experience',
    'Preferred Technologies',
    'Work Authorization (Visa Status)',
    'Preferred Industry',
    'Expected Benefits',
    'References',
    'Cover Letter Content',
    'Softwares Known',
    'Publications',
    'Hobbies/Interests',
    'Volunteer Experience',
    'Driving License',
    'Languages (Proficiency)',
    'Special Awards',
    'LinkedIn Followers',
    'GitHub Stars',
    'Coding Challenge Scores (HackerRank/LeetCode)',
    'Management Experience (Years)',
    'Team Size Managed',
    'Detected Extra Fields',
]

def get_missing_fields(extracted_data):
    return ', '.join([field for field in extracted_data.keys() if field not in FIELDS])
